### ISSUE TITLE
Tutorial code does not work with pip version

### ISSUE THREAD

**Issue by fredcallaway** [neurosynth/neurosynth-data#2]
This might be a local problem but I could not run code like `from neurosynth import Dataset` after installing with pip.  (I had to use `from neurosynth.base.dataset import Dataset`). The problem was fixed when I installed from source.

**Comment by tyarkoni** [comment]
Thanks for catching that; I haven't synced with PyPI in a while. Will bump the version shortly and then it should work.

**Comment by tyarkoni** [comment]
Should be in sync now, so if you pip install neurosynth --upgrade, the demo should run properly. If not, please re-open this issue. Thanks!
